# Generated by Django 4.2.7 on 2023-11-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_run', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=35)),
                ('s_nombre', models.CharField(blank=True, max_length=35, null=True)),
                ('ap_paterno', models.CharField(max_length=35)),
                ('ap_materno', models.CharField(max_length=35)),
                ('fec_nac', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dir', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_dic', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('run_due', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_run', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=35)),
                ('s_nombre', models.CharField(blank=True, max_length=35, null=True)),
                ('ap_paterno', models.CharField(max_length=35)),
                ('ap_materno', models.CharField(max_length=35)),
                ('fec_nac', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dueno',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=35)),
                ('modelo', models.CharField(max_length=35)),
                ('color', models.CharField(max_length=35)),
                ('run_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.cliente')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('num_tarjeta', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('cvv', models.CharField(max_length=3)),
                ('run_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.cliente')),
            ],
            options={
                'db_table': 'tarjeta',
            },
        ),
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id_est', models.IntegerField(primary_key=True, serialize=False)),
                ('tarifa', models.IntegerField()),
                ('id_dir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.direccion')),
                ('run_due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.dueno')),
            ],
            options={
                'db_table': 'estacionamiento',
            },
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arr', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inic', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('id_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.estacionamiento')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.vehiculo')),
            ],
            options={
                'db_table': 'arriendo',
            },
        ),
    ]
