# Generated by Django 4.2.7 on 2023-11-21 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.AddField(
            model_name='arriendo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('culminado', 'Culminado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=35)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.marca')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje', models.IntegerField()),
                ('comentario', models.TextField()),
                ('id_arr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.arriendo')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiEstacionamiento.modelo'),
        ),
    ]
