# Generated by Django 4.2.2 on 2023-11-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0003_rename_ap_materno_cliente_apaterno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendo',
            old_name='id_arr',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='id_calificacion',
            new_name='cali',
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='id_arr',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='nombre_dic',
            new_name='direc',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='id_dir',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='id_est',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='run_due',
            new_name='run',
        ),
    ]
