# Generated by Django 4.2.2 on 2023-11-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0005_arriendowardado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendowardado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
