# Generated by Django 4.2.2 on 2023-12-12 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MiEstacionamiento', '0006_alter_arriendowardado_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacionamiento',
            name='run',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='run',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='run',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='ide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='ide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Dueno',
        ),
    ]
