# Generated by Django 4.2.2 on 2023-12-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0008_rename_id_est_arriendo_estacionamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacionamiento',
            old_name='tarifa',
            new_name='valorMinu',
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
