# Generated by Django 4.2.2 on 2023-12-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0010_alter_estacionamiento_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='estado',
        ),
        migrations.AddField(
            model_name='estacionamiento',
            name='estado',
            field=models.CharField(choices=[('ocupado', 'Ocupado'), ('disponible', 'Disponible'), ('cerrado', 'Cerrado')], default='disponible', max_length=20),
        ),
    ]
