# Generated by Django 4.2.7 on 2023-12-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0011_remove_arriendo_estado_estacionamiento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendowardado',
            name='estatus',
        ),
    ]
