# Generated by Django 4.2.7 on 2023-12-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0014_remove_modelo_marca_remove_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
