# Generated by Django 4.2.7 on 2023-12-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiEstacionamiento', '0015_alter_arriendo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='arriendoWardado',
        ),
    ]
